### ISSUE TITLE
customize order within workflow

### ISSUE THREAD

**Issue by ijlyttle** [ijlyttle/projthis#52]
Following a question from @andeek, I wonder if a workflow could have an optional `_projthis.yml` file for customizing the rendering order:

```yml
first: 
  - run-me-first.Rmd
  - me-second.Rmd
last:
  - penultimate.Rmd
  - last-one.Rmd
```

Everything not specified could be run in alphabetical order, with `README.Rmd` last.
