### ISSUE TITLE
can we capture python dependencies?

### ISSUE THREAD

**Issue by ijlyttle** [ijlyttle/projthis#55]
could we piggyback off of renv's capabilities here?

cc @jonthegeek

**Comment by ijlyttle** [comment]
As far as renv goes, I think we would need access to this internal renv function:

https://github.com/rstudio/renv/blob/96d0a62fa2a534470b6fc84cb36ba0ae595f1460/R/python.R#L178

Even with access, I wonder if it requires that your project use renv for everything to "just work".

**Comment by ijlyttle** [comment]
There's a field in DESCRIPTION file called `SystemRequirements`; it is free form.
We could imagine something like:

```
SystemRequirements: Python 3.8.6
```

We can also do something like this in actions:

```yaml
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8.6
          cache: pip # caching pip dependencies

      - run: pip install -r requirements.txt
```

We can also imagine a way to have the action read the DESCRIPTION file, get, [then set](https://stackoverflow.com/a/61258467), the version of python.

`pip install -r requirements.txt`, as I understand, is used for virtual environments; need to consider how to make that easier without getting in the way.
